### ISSUE TITLE
Slack Integration Error

### ISSUE THREAD

**Issue by yuyang-zhong** [xingyaoww/gif-reply-slack-bot#1]
Hi there,

It seems like Pepe the Gif Bot is no longer working in Slack. Pepe no longer respond to messages as configured previously.

Slash commands are returning errors of "failed with the error "dispatch_failed""

New integrations (add to workspace) lead to 502 bad gateway error.

**Comment by xingyaoww** [comment]
Thanks for reporting the issue! 
It should be fixed by now -- Please let me know if it is still not working!
